/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DAO;


import Conexion.Conexion;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;
import Modelo.Alumno;
import Modelo.FlujoEstado;
import Modelo.Solicitud;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;

/**
 *
 * @author Alvaro
 */
public class DAOMail {

    private Connection conn = new Conexion().Conectar();
    

    public void sendEmail(Alumno al, Solicitud soli) throws UnsupportedEncodingException {
        //Variable para definir el próximo estado de la solicitud.
        int proxEstado = 1;
        
        DAOUsuario dusu = new DAOUsuario();
        DAOSolicitud daosoli = new DAOSolicitud();
        DAOFlujoEstado fe = new DAOFlujoEstado();
        ArrayList<FlujoEstado> listaFe = fe.traerFlujoEstrados(soli.getIdflujo());
        int idEstado = daosoli.consultarEstado(soli.getIdSolicitud());
        for (FlujoEstado fl : listaFe) {
            if (fl.getIdEstdado() == idEstado) {
                int update = listaFe.get(listaFe.indexOf(fl) + 1).getIdEstdado();
                proxEstado = update;
            }
        }
        
        System.out.println(al.getCARRERA_ALUMNO());
        String mensaje = "<!Doctype html>\n"
                + "<html lang='es'>\n"
                + "  <head>\n"
                + "    <meta name=\"viewport\" content=\"width=device-width\" />\n"
                + "    <meta concent-type='UTF-8' />\n"
                + "    <title>Simple Transactional Email</title>\n"
                + "    <style>\n"
                + "      /* -------------------------------------\n"
                + "          GLOBAL RESETS\n"
                + "      ------------------------------------- */\n"
                + "      \n"
                + "      /*All the styling goes here*/\n"
                + "      \n"
                + "      img {\n"
                + "        border: none;\n"
                + "        -ms-interpolation-mode: bicubic;\n"
                + "        max-width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      body {\n"
                + "        background-color: #f6f6f6;\n"
                + "        font-family: sans-serif;\n"
                + "        -webkit-font-smoothing: antialiased;\n"
                + "        font-size: 14px;\n"
                + "        line-height: 1.4;\n"
                + "        margin: 0;\n"
                + "        padding: 0;\n"
                + "        -ms-text-size-adjust: 100%;\n"
                + "        -webkit-text-size-adjust: 100%; \n"
                + "      }\n"
                + "\n"
                + "      table {\n"
                + "      font-family: arial, sans-serif;\n"
                + "      border-collapse: collapse;\n"
                + "      width: 100%;\n"
                + "      }\n"
                + "\n"
                + "      td, th {\n"
                + "      border: 1px solid #dddddd;\n"
                + "      text-align: left;\n"
                + "      padding: 8px;\n"
                + "      } \n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          BODY & CONTAINER\n"
                + "      ------------------------------------- */\n"
                + "\n"
                + "      .body {\n"
                + "        background-color: #f6f6f6;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */\n"
                + "      .container {\n"
                + "        display: block;\n"
                + "        margin: 0 auto !important;\n"
                + "        /* makes it centered */\n"
                + "        max-width: 580px;\n"
                + "        padding: 10px;\n"
                + "        width: 600px; \n"
                + "      }\n"
                + "\n"
                + "      /* This should also be a block element, so that it will fill 100% of the .container */\n"
                + "      .content {\n"
                + "        box-sizing: border-box;\n"
                + "        display: block;\n"
                + "        margin: 0 auto;\n"
                + "        max-width: 580px;\n"
                + "        padding: 10px; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          HEADER, FOOTER, MAIN\n"
                + "      ------------------------------------- */\n"
                + "      .main {\n"
                + "        background: #ffffff;\n"
                + "        border-radius: 3px;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      .wrapper {\n"
                + "        box-sizing: border-box;\n"
                + "        padding: 20px; \n"
                + "      }\n"
                + "\n"
                + "      .content-block {\n"
                + "        padding-bottom: 10px;\n"
                + "        padding-top: 10px;\n"
                + "      }\n"
                + "\n"
                + "      .footer {\n"
                + "        clear: both;\n"
                + "        margin-top: 10px;\n"
                + "        text-align: center;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "        .footer td,\n"
                + "        .footer p,\n"
                + "        .footer span,\n"
                + "        .footer a {\n"
                + "          color: #999999;\n"
                + "          font-size: 12px;\n"
                + "          text-align: center; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          TYPOGRAPHY\n"
                + "      ------------------------------------- */\n"
                + "      h1,\n"
                + "      h2,\n"
                + "      h3,\n"
                + "      h4 {\n"
                + "        color: #000000;\n"
                + "        font-family: sans-serif;\n"
                + "        font-weight: 400;\n"
                + "        line-height: 1.4;\n"
                + "        margin: 0;\n"
                + "        margin-bottom: 30px; \n"
                + "      }\n"
                + "\n"
                + "      h1 {\n"
                + "        font-size: 35px;\n"
                + "        font-weight: 300;\n"
                + "        text-align: center;\n"
                + "        text-transform: capitalize; \n"
                + "      }\n"
                + "\n"
                + "      p,\n"
                + "      ul,\n"
                + "      ol {\n"
                + "        font-family: sans-serif;\n"
                + "        font-size: 14px;\n"
                + "        font-weight: normal;\n"
                + "        margin: 0;\n"
                + "        margin-bottom: 15px; \n"
                + "      }\n"
                + "        p li,\n"
                + "        ul li,\n"
                + "        ol li {\n"
                + "          list-style-position: inside;\n"
                + "          margin-left: 5px; \n"
                + "      }\n"
                + "\n"
                + "      a {\n"
                + "        color: #3498db;\n"
                + "        text-decoration: underline; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          BUTTONS\n"
                + "      ------------------------------------- */\n"
                + "      .btn {\n"
                + "        box-sizing: border-box;\n"
                + "        width: 100%; }\n"
                + "        .btn > tbody > tr > td {\n"
                + "          padding-bottom: 15px; }\n"
                + "        .btn table {\n"
                + "          width: auto; \n"
                + "      }\n"
                + "        .btn table td {\n"
                + "          background-color: #ffffff;\n"
                + "          border-radius: 5px;\n"
                + "          text-align: center; \n"
                + "      }\n"
                + "        .btn a {\n"
                + "          background-color: #ffffff;\n"
                + "          border: solid 1px #3498db;\n"
                + "          border-radius: 5px;\n"
                + "          box-sizing: border-box;\n"
                + "          color: #3498db;\n"
                + "          cursor: pointer;\n"
                + "          display: inline-block;\n"
                + "          font-size: 14px;\n"
                + "          font-weight: bold;\n"
                + "          margin: 0;\n"
                + "          padding: 12px 25px;\n"
                + "          text-decoration: none;\n"
                + "          text-transform: capitalize; \n"
                + "      }\n"
                + "\n"
                + "      .btn-primary table td {\n"
                + "        background-color: #3498db; \n"
                + "      }\n"
                + "\n"
                + "      .btn-primary a {\n"
                + "        background-color: #3498db;\n"
                + "        border-color: #3498db;\n"
                + "        color: #ffffff; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          OTHER STYLES THAT MIGHT BE USEFUL\n"
                + "      ------------------------------------- */\n"
                + "      .last {\n"
                + "        margin-bottom: 0; \n"
                + "      }\n"
                + "\n"
                + "      .first {\n"
                + "        margin-top: 0; \n"
                + "      }\n"
                + "\n"
                + "      .align-center {\n"
                + "        text-align: center; \n"
                + "      }\n"
                + "\n"
                + "      .align-right {\n"
                + "        text-align: right; \n"
                + "      }\n"
                + "\n"
                + "      .align-left {\n"
                + "        text-align: left; \n"
                + "      }\n"
                + "\n"
                + "      .clear {\n"
                + "        clear: both; \n"
                + "      }\n"
                + "\n"
                + "      .mt0 {\n"
                + "        margin-top: 0; \n"
                + "      }\n"
                + "\n"
                + "      .mb0 {\n"
                + "        margin-bottom: 0; \n"
                + "      }\n"
                + "\n"
                + "      .preheader {\n"
                + "        color: transparent;\n"
                + "        display: none;\n"
                + "        height: 0;\n"
                + "        max-height: 0;\n"
                + "        max-width: 0;\n"
                + "        opacity: 0;\n"
                + "        overflow: hidden;\n"
                + "        mso-hide: all;\n"
                + "        visibility: hidden;\n"
                + "        width: 0; \n"
                + "      }\n"
                + "\n"
                + "      .powered-by a {\n"
                + "        text-decoration: none; \n"
                + "      }\n"
                + "\n"
                + "      hr {\n"
                + "        border: 0;\n"
                + "        border-bottom: 1px solid #f6f6f6;\n"
                + "        margin: 20px 0; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          RESPONSIVE AND MOBILE FRIENDLY STYLES\n"
                + "      ------------------------------------- */\n"
                + "      @media only screen and (max-width: 620px) {\n"
                + "        table[class=body] h1 {\n"
                + "          font-size: 28px !important;\n"
                + "          margin-bottom: 10px !important; \n"
                + "        }\n"
                + "        table[class=body] p,\n"
                + "        table[class=body] ul,\n"
                + "        table[class=body] ol,\n"
                + "        table[class=body] td,\n"
                + "        table[class=body] span,\n"
                + "        table[class=body] a {\n"
                + "          font-size: 16px !important; \n"
                + "        }\n"
                + "        table[class=body] .wrapper,\n"
                + "        table[class=body] .article {\n"
                + "          padding: 10px !important; \n"
                + "        }\n"
                + "        table[class=body] .content {\n"
                + "          padding: 0 !important; \n"
                + "        }\n"
                + "        table[class=body] .container {\n"
                + "          padding: 0 !important;\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .main {\n"
                + "          border-left-width: 0 !important;\n"
                + "          border-radius: 0 !important;\n"
                + "          border-right-width: 0 !important; \n"
                + "        }\n"
                + "        table[class=body] .btn table {\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .btn a {\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .img-responsive {\n"
                + "          height: auto !important;\n"
                + "          max-width: 100% !important;\n"
                + "          width: auto !important; \n"
                + "        }\n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          PRESERVE THESE STYLES IN THE HEAD\n"
                + "      ------------------------------------- */\n"
                + "      @media all {\n"
                + "        .ExternalClass {\n"
                + "          width: 100%; \n"
                + "        }\n"
                + "        .ExternalClass,\n"
                + "        .ExternalClass p,\n"
                + "        .ExternalClass span,\n"
                + "        .ExternalClass font,\n"
                + "        .ExternalClass td,\n"
                + "        .ExternalClass div {\n"
                + "          line-height: 100%; \n"
                + "        }\n"
                + "        .apple-link a {\n"
                + "          color: inherit !important;\n"
                + "          font-family: inherit !important;\n"
                + "          font-size: inherit !important;\n"
                + "          font-weight: inherit !important;\n"
                + "          line-height: inherit !important;\n"
                + "          text-decoration: none !important; \n"
                + "        }\n"
                + "        #MessageViewBody a {\n"
                + "          color: inherit;\n"
                + "          text-decoration: none;\n"
                + "          font-size: inherit;\n"
                + "          font-family: inherit;\n"
                + "          font-weight: inherit;\n"
                + "          line-height: inherit;\n"
                + "        }\n"
                + "        .btn-primary table td:hover {\n"
                + "          background-color: #34495e !important; \n"
                + "        }\n"
                + "        .btn-primary a:hover {\n"
                + "          background-color: #34495e !important;\n"
                + "          border-color: #34495e !important; \n"
                + "        } \n"
                + "      }\n"
                + "\n"
                + "    </style>\n"
                + "  </head>\n"
                + "  <body class=\"\">\n"
                + "    <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\">\n"
                + "      <tr>\n"
                + "        <td>&nbsp;</td>\n"
                + "        <td class=\"container\">\n"
                + "          <div class=\"content\">\n"
                + "\n"
                + "            <!-- START CENTERED WHITE CONTAINER -->\n"
                + "            <table role=\"presentation\" class=\"main\">\n"
                + "\n"
                + "              <!-- START MAIN CONTENT AREA -->\n"
                + "              <tr>\n"
                + "                <td class=\"wrapper\">\n"
                + "                    <h2>Tipo Solicitud: \n" + joinNombreSoli(soli.getIdflujo())
                + "                      </h2>\n"
                + "                      <h2>\n"
                + "                          COMPROBANTE DE SOLICITUD \n"
                + "                          FOLIO DE TRANSACCIÓN N°" + soli.getIdSolicitud()+ "\n" + "" + dia + " del " + mes + " de " + annio + "\n"
                + "                      </h2>\n"
                + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                    \n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Alumno:\n"
                + "                      </th>\n"
                + "                      <td>\n" + al.getNOMBRE_ALUMNO()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Rut:\n"
                + "                      </th>\n"
                + "                      <td>\n" + al.getRUT_ALUMNO().replaceAll("[.-]", "")
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Establecimiento:\n"
                + "                      </th>\n"
                + "                      <td>\n"
                + "                        DuocUC: Antonio Varas\n"
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Jornada:\n"
                + "                      </th>\n"
                + "                      <td>\n" + joinJornada(al.getID_JORNADA())
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Carrera:\n"
                + "                      </th>\n"
                + "                      <td>\n" + al.getCARRERA_ALUMNO()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Telefono:\n"
                + "                      </th>\n"
                + "                      <td>\n +56 " + al.getTELEFONO()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Creador de la solicitud:\n"
                + "                      </th>\n"
                + "                      <td>\n" + dusu.traerUsuario(soli.getIdUsuarioCreador()).getNombre()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Responsable actual:\n"
                + "                      </th>\n"
                + "                      <td>\n" + dusu.traerUsuario(soli.getIdUsuarioResponsable()).getNombre()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Estado actual:\n"
                + "                      </th>\n"
                + "                      <td>\n" + daosoli.consultarNombreEstado(soli.getCodEstado())
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Próximo estado:\n"
                + "                      </th>\n"
                + "                      <td>\n" + daosoli.consultarNombreEstado(proxEstado)
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Fecha:\n"
                + "                      </th>\n"
                + "                      <td> \n" + dia + " del " + mes + " de " + annio
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "Descripción:"
                + "                      </th>\n"
                + "                      <td>\n" + soli.getDescripcion()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "                  </table>\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "              <tr>\n"
                + "                <th>\n"
                + "                    <span>\n"
                + "                        Se le informará oportunamente a su teléfono o correo \n"
                + "                        electrónico, la fecha que debe retirar lo solicitado \n"
                + "                        o el estado de su solicitud.\n"
                + "                    </span>\n"
                + "                    <span>\n"
                + "                        Por favor no responder este correo, si tiene \n"
                + "                        dudas o necesita consultar por su estado,  enviar \n"
                + "                        mail a <a href=\"mailto: csa_avaras@duoc.cl\">csa_avaras@duoc.cl</a> \n"
                + "                    </span>\n"
                + "                </th>\n"
                + "              </tr>\n"
                + "            <!-- END MAIN CONTENT AREA -->\n"
                + "            </table>\n"
                + "            <!-- END CENTERED WHITE CONTAINER -->\n"
                + "            <!-- START FOOTER -->\n"
                + "            <div class=\"footer\">\n"
                + "                \n"
                + "              <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                <tr>\n"
                + "                  <td class=\"content-block\">\n"
                + "                    <span class=\"apple-link\">DuocUC: Sede Antonio Varas, Antonio Varas 666 Providencia, Región Metropolitana</span>\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "                <tr>\n"
                + "                  <td class=\"content-block powered-by\">\n"
                + "                    Powered by <a href=\"http://htmlemail.io\">HTMLemail</a>.\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "              </table>\n"
                + "            </div>\n"
                + "            <!-- END FOOTER -->\n"
                + "\n"
                + "          </div>\n"
                + "        </td>\n"
                + "        <td>&nbsp;</td>\n"
                + "      </tr>\n"
                + "    </table>\n"
                + "  </body>\n"
                + "</html>";

        final String username = "webdocspruebas@gmail.com";
        final String password = "123duoc456";

        Properties prop = new Properties();
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "587");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.starttls.enable", "true"); //TLS
        prop.put("mail.smtp.ssl.trust", "*");

        Session session = Session.getInstance(prop,
                new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {

            Message message = new MimeMessage(session);
            message.setSubject("Notificacion solicitud");
            message.setContent(mensaje, "text/html; charset=UTF-8");
            message.setFrom(new InternetAddress(username,"Solicitud Duoc UC"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(al.getCORREO_ALUMNO()));

            Transport.send(message);

            System.out.println("Done");

        } catch (MessagingException e) {
            e.printStackTrace();
        }

    }
    
public void sendEmailRechazar(Alumno al, Solicitud soli) throws UnsupportedEncodingException {
        //Variable para definir el próximo estado de la solicitud.
        int proxEstado = 5;
        
        DAOUsuario dusu = new DAOUsuario();
        DAOSolicitud daosoli = new DAOSolicitud();
        
        System.out.println(al.getCARRERA_ALUMNO());
        String mensaje = "<!Doctype html>\n"
                + "<html lang='es'>\n"
                + "  <head>\n"
                + "    <meta name=\"viewport\" content=\"width=device-width\" />\n"
                + "    <meta concent-type='UTF-8' />\n"
                + "    <title>Simple Transactional Email</title>\n"
                + "    <style>\n"
                + "      /* -------------------------------------\n"
                + "          GLOBAL RESETS\n"
                + "      ------------------------------------- */\n"
                + "      \n"
                + "      /*All the styling goes here*/\n"
                + "      \n"
                + "      img {\n"
                + "        border: none;\n"
                + "        -ms-interpolation-mode: bicubic;\n"
                + "        max-width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      body {\n"
                + "        background-color: #f6f6f6;\n"
                + "        font-family: sans-serif;\n"
                + "        -webkit-font-smoothing: antialiased;\n"
                + "        font-size: 14px;\n"
                + "        line-height: 1.4;\n"
                + "        margin: 0;\n"
                + "        padding: 0;\n"
                + "        -ms-text-size-adjust: 100%;\n"
                + "        -webkit-text-size-adjust: 100%; \n"
                + "      }\n"
                + "\n"
                + "      table {\n"
                + "      font-family: arial, sans-serif;\n"
                + "      border-collapse: collapse;\n"
                + "      width: 100%;\n"
                + "      }\n"
                + "\n"
                + "      td, th {\n"
                + "      border: 1px solid #dddddd;\n"
                + "      text-align: left;\n"
                + "      padding: 8px;\n"
                + "      } \n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          BODY & CONTAINER\n"
                + "      ------------------------------------- */\n"
                + "\n"
                + "      .body {\n"
                + "        background-color: #f6f6f6;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */\n"
                + "      .container {\n"
                + "        display: block;\n"
                + "        margin: 0 auto !important;\n"
                + "        /* makes it centered */\n"
                + "        max-width: 580px;\n"
                + "        padding: 10px;\n"
                + "        width: 600px; \n"
                + "      }\n"
                + "\n"
                + "      /* This should also be a block element, so that it will fill 100% of the .container */\n"
                + "      .content {\n"
                + "        box-sizing: border-box;\n"
                + "        display: block;\n"
                + "        margin: 0 auto;\n"
                + "        max-width: 580px;\n"
                + "        padding: 10px; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          HEADER, FOOTER, MAIN\n"
                + "      ------------------------------------- */\n"
                + "      .main {\n"
                + "        background: #ffffff;\n"
                + "        border-radius: 3px;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      .wrapper {\n"
                + "        box-sizing: border-box;\n"
                + "        padding: 20px; \n"
                + "      }\n"
                + "\n"
                + "      .content-block {\n"
                + "        padding-bottom: 10px;\n"
                + "        padding-top: 10px;\n"
                + "      }\n"
                + "\n"
                + "      .footer {\n"
                + "        clear: both;\n"
                + "        margin-top: 10px;\n"
                + "        text-align: center;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "        .footer td,\n"
                + "        .footer p,\n"
                + "        .footer span,\n"
                + "        .footer a {\n"
                + "          color: #999999;\n"
                + "          font-size: 12px;\n"
                + "          text-align: center; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          TYPOGRAPHY\n"
                + "      ------------------------------------- */\n"
                + "      h1,\n"
                + "      h2,\n"
                + "      h3,\n"
                + "      h4 {\n"
                + "        color: #000000;\n"
                + "        font-family: sans-serif;\n"
                + "        font-weight: 400;\n"
                + "        line-height: 1.4;\n"
                + "        margin: 0;\n"
                + "        margin-bottom: 30px; \n"
                + "      }\n"
                + "\n"
                + "      h1 {\n"
                + "        font-size: 35px;\n"
                + "        font-weight: 300;\n"
                + "        text-align: center;\n"
                + "        text-transform: capitalize; \n"
                + "      }\n"
                + "\n"
                + "      p,\n"
                + "      ul,\n"
                + "      ol {\n"
                + "        font-family: sans-serif;\n"
                + "        font-size: 14px;\n"
                + "        font-weight: normal;\n"
                + "        margin: 0;\n"
                + "        margin-bottom: 15px; \n"
                + "      }\n"
                + "        p li,\n"
                + "        ul li,\n"
                + "        ol li {\n"
                + "          list-style-position: inside;\n"
                + "          margin-left: 5px; \n"
                + "      }\n"
                + "\n"
                + "      a {\n"
                + "        color: #3498db;\n"
                + "        text-decoration: underline; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          BUTTONS\n"
                + "      ------------------------------------- */\n"
                + "      .btn {\n"
                + "        box-sizing: border-box;\n"
                + "        width: 100%; }\n"
                + "        .btn > tbody > tr > td {\n"
                + "          padding-bottom: 15px; }\n"
                + "        .btn table {\n"
                + "          width: auto; \n"
                + "      }\n"
                + "        .btn table td {\n"
                + "          background-color: #ffffff;\n"
                + "          border-radius: 5px;\n"
                + "          text-align: center; \n"
                + "      }\n"
                + "        .btn a {\n"
                + "          background-color: #ffffff;\n"
                + "          border: solid 1px #3498db;\n"
                + "          border-radius: 5px;\n"
                + "          box-sizing: border-box;\n"
                + "          color: #3498db;\n"
                + "          cursor: pointer;\n"
                + "          display: inline-block;\n"
                + "          font-size: 14px;\n"
                + "          font-weight: bold;\n"
                + "          margin: 0;\n"
                + "          padding: 12px 25px;\n"
                + "          text-decoration: none;\n"
                + "          text-transform: capitalize; \n"
                + "      }\n"
                + "\n"
                + "      .btn-primary table td {\n"
                + "        background-color: #3498db; \n"
                + "      }\n"
                + "\n"
                + "      .btn-primary a {\n"
                + "        background-color: #3498db;\n"
                + "        border-color: #3498db;\n"
                + "        color: #ffffff; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          OTHER STYLES THAT MIGHT BE USEFUL\n"
                + "      ------------------------------------- */\n"
                + "      .last {\n"
                + "        margin-bottom: 0; \n"
                + "      }\n"
                + "\n"
                + "      .first {\n"
                + "        margin-top: 0; \n"
                + "      }\n"
                + "\n"
                + "      .align-center {\n"
                + "        text-align: center; \n"
                + "      }\n"
                + "\n"
                + "      .align-right {\n"
                + "        text-align: right; \n"
                + "      }\n"
                + "\n"
                + "      .align-left {\n"
                + "        text-align: left; \n"
                + "      }\n"
                + "\n"
                + "      .clear {\n"
                + "        clear: both; \n"
                + "      }\n"
                + "\n"
                + "      .mt0 {\n"
                + "        margin-top: 0; \n"
                + "      }\n"
                + "\n"
                + "      .mb0 {\n"
                + "        margin-bottom: 0; \n"
                + "      }\n"
                + "\n"
                + "      .preheader {\n"
                + "        color: transparent;\n"
                + "        display: none;\n"
                + "        height: 0;\n"
                + "        max-height: 0;\n"
                + "        max-width: 0;\n"
                + "        opacity: 0;\n"
                + "        overflow: hidden;\n"
                + "        mso-hide: all;\n"
                + "        visibility: hidden;\n"
                + "        width: 0; \n"
                + "      }\n"
                + "\n"
                + "      .powered-by a {\n"
                + "        text-decoration: none; \n"
                + "      }\n"
                + "\n"
                + "      hr {\n"
                + "        border: 0;\n"
                + "        border-bottom: 1px solid #f6f6f6;\n"
                + "        margin: 20px 0; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          RESPONSIVE AND MOBILE FRIENDLY STYLES\n"
                + "      ------------------------------------- */\n"
                + "      @media only screen and (max-width: 620px) {\n"
                + "        table[class=body] h1 {\n"
                + "          font-size: 28px !important;\n"
                + "          margin-bottom: 10px !important; \n"
                + "        }\n"
                + "        table[class=body] p,\n"
                + "        table[class=body] ul,\n"
                + "        table[class=body] ol,\n"
                + "        table[class=body] td,\n"
                + "        table[class=body] span,\n"
                + "        table[class=body] a {\n"
                + "          font-size: 16px !important; \n"
                + "        }\n"
                + "        table[class=body] .wrapper,\n"
                + "        table[class=body] .article {\n"
                + "          padding: 10px !important; \n"
                + "        }\n"
                + "        table[class=body] .content {\n"
                + "          padding: 0 !important; \n"
                + "        }\n"
                + "        table[class=body] .container {\n"
                + "          padding: 0 !important;\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .main {\n"
                + "          border-left-width: 0 !important;\n"
                + "          border-radius: 0 !important;\n"
                + "          border-right-width: 0 !important; \n"
                + "        }\n"
                + "        table[class=body] .btn table {\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .btn a {\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .img-responsive {\n"
                + "          height: auto !important;\n"
                + "          max-width: 100% !important;\n"
                + "          width: auto !important; \n"
                + "        }\n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          PRESERVE THESE STYLES IN THE HEAD\n"
                + "      ------------------------------------- */\n"
                + "      @media all {\n"
                + "        .ExternalClass {\n"
                + "          width: 100%; \n"
                + "        }\n"
                + "        .ExternalClass,\n"
                + "        .ExternalClass p,\n"
                + "        .ExternalClass span,\n"
                + "        .ExternalClass font,\n"
                + "        .ExternalClass td,\n"
                + "        .ExternalClass div {\n"
                + "          line-height: 100%; \n"
                + "        }\n"
                + "        .apple-link a {\n"
                + "          color: inherit !important;\n"
                + "          font-family: inherit !important;\n"
                + "          font-size: inherit !important;\n"
                + "          font-weight: inherit !important;\n"
                + "          line-height: inherit !important;\n"
                + "          text-decoration: none !important; \n"
                + "        }\n"
                + "        #MessageViewBody a {\n"
                + "          color: inherit;\n"
                + "          text-decoration: none;\n"
                + "          font-size: inherit;\n"
                + "          font-family: inherit;\n"
                + "          font-weight: inherit;\n"
                + "          line-height: inherit;\n"
                + "        }\n"
                + "        .btn-primary table td:hover {\n"
                + "          background-color: #34495e !important; \n"
                + "        }\n"
                + "        .btn-primary a:hover {\n"
                + "          background-color: #34495e !important;\n"
                + "          border-color: #34495e !important; \n"
                + "        } \n"
                + "      }\n"
                + "\n"
                + "    </style>\n"
                + "  </head>\n"
                + "  <body class=\"\">\n"
                + "    <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\">\n"
                + "      <tr>\n"
                + "        <td>&nbsp;</td>\n"
                + "        <td class=\"container\">\n"
                + "          <div class=\"content\">\n"
                + "\n"
                + "            <!-- START CENTERED WHITE CONTAINER -->\n"
                + "            <table role=\"presentation\" class=\"main\">\n"
                + "\n"
                + "              <!-- START MAIN CONTENT AREA -->\n"
                + "              <tr>\n"
                + "                <td class=\"wrapper\">\n"
                + "                    <h2>Tipo Solicitud: \n" + joinNombreSoli(soli.getIdflujo())
                + "                      </h2>\n"
                + "                      <h2>\n"
                + "                          COMPROBANTE DE SOLICITUD \n"
                + "                          FOLIO DE TRANSACCIÓN N°" + soli.getIdSolicitud()+ "\n" + "" + dia + " del " + mes + " de " + annio + "\n"
                + "                          RESOLUCION DE SOLICITUD: RECHAZADA"
                + "</h2>\n"
                + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                    \n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Alumno:\n"
                + "                      </th>\n"
                + "                      <td>\n" + al.getNOMBRE_ALUMNO()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Rut:\n"
                + "                      </th>\n"
                + "                      <td>\n" + al.getRUT_ALUMNO().replaceAll("[.-]", "")
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Establecimiento:\n"
                + "                      </th>\n"
                + "                      <td>\n"
                + "                        DuocUC: Antonio Varas\n"
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Jornada:\n"
                + "                      </th>\n"
                + "                      <td>\n" + joinJornada(al.getID_JORNADA())
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Carrera:\n"
                + "                      </th>\n"
                + "                      <td>\n" + al.getCARRERA_ALUMNO()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Telefono:\n"
                + "                      </th>\n"
                + "                      <td>\n +56 " + al.getTELEFONO()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Creador de la solicitud:\n"
                + "                      </th>\n"
                + "                      <td>\n" + dusu.traerUsuario(soli.getIdUsuarioCreador()).getNombre()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Responsable actual:\n"
                + "                      </th>\n"
                + "                      <td>\n" + dusu.traerUsuario(soli.getIdUsuarioResponsable()).getNombre()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Estado actual:\n"
                + "                      </th>\n"
                + "                      <td>\n" + daosoli.consultarNombreEstado(soli.getCodEstado())
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Próximo estado:\n"
                + "                      </th>\n"
                + "                      <td>\n" + daosoli.consultarNombreEstado(proxEstado)
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Fecha:\n"
                + "                      </th>\n"
                + "                      <td> \n" + dia + " del " + mes + " de " + annio
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "Descripción:"
                + "                      </th>\n"
                + "                      <td>\n" + soli.getDescripcion()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "Motivo del rechazo:"
                + "                      </th>\n"
                + "                      <td>\n" + joinMotivo(soli.getIdMotivo())
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "Observaciones:"
                + "                      </th>\n"
                + "                      <td>\n" + soli.getObservacion()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "                  </table>\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "              <tr>\n"
                + "                <th>\n"
                + "                    <span>\n"
                + "                        Se le informará oportunamente a su teléfono o correo \n"
                + "                        electrónico, la fecha que debe retirar lo solicitado \n"
                + "                        o el estado de su solicitud.\n"
                + "                    </span>\n"
                + "                    <span>\n"
                + "                        Por favor no responder este correo, si tiene \n"
                + "                        dudas o necesita consultar por su estado,  enviar \n"
                + "                        mail a <a href=\"mailto: csa_avaras@duoc.cl\">csa_avaras@duoc.cl</a> \n"
                + "                    </span>\n"
                + "                </th>\n"
                + "              </tr>\n"
                + "            <!-- END MAIN CONTENT AREA -->\n"
                + "            </table>\n"
                + "            <!-- END CENTERED WHITE CONTAINER -->\n"
                + "            <!-- START FOOTER -->\n"
                + "            <div class=\"footer\">\n"
                + "                \n"
                + "              <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                <tr>\n"
                + "                  <td class=\"content-block\">\n"
                + "                    <span class=\"apple-link\">DuocUC: Sede Antonio Varas, Antonio Varas 666 Providencia, Región Metropolitana</span>\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "                <tr>\n"
                + "                  <td class=\"content-block powered-by\">\n"
                + "                    Powered by <a href=\"http://htmlemail.io\">HTMLemail</a>.\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "              </table>\n"
                + "            </div>\n"
                + "            <!-- END FOOTER -->\n"
                + "\n"
                + "          </div>\n"
                + "        </td>\n"
                + "        <td>&nbsp;</td>\n"
                + "      </tr>\n"
                + "    </table>\n"
                + "  </body>\n"
                + "</html>";

        final String username = "webdocspruebas@gmail.com";
        final String password = "123duoc456";

        Properties prop = new Properties();
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "587");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.starttls.enable", "true"); //TLS
        prop.put("mail.smtp.ssl.trust", "*");

        Session session = Session.getInstance(prop,
                new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {

            Message message = new MimeMessage(session);
            message.setSubject("Notificacion solicitud");
            message.setContent(mensaje, "text/html; charset=UTF-8");
            message.setFrom(new InternetAddress(username,"Solicitud Duoc UC"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(al.getCORREO_ALUMNO()));

            Transport.send(message);

            System.out.println("Done");

        } catch (MessagingException e) {
            e.printStackTrace();
        }

    }
    
    public void sendEmailAprobar(Alumno al, Solicitud soli) throws UnsupportedEncodingException {
        //Variable para definir el próximo estado de la solicitud.
        int proxEstado = 0;
        
        DAOUsuario dusu = new DAOUsuario();
        DAOSolicitud daosoli = new DAOSolicitud();
        DAOFlujoEstado fe = new DAOFlujoEstado();
        ArrayList<FlujoEstado> listaFe = fe.traerFlujoEstrados(soli.getIdflujo());
        int idEstado = daosoli.consultarEstado(soli.getIdSolicitud());
        for (FlujoEstado fl : listaFe) {
            if (fl.getIdEstdado() == idEstado) {
                int update = listaFe.get(listaFe.indexOf(fl) + 1).getIdEstdado();
                proxEstado = update;
            }
        }
        
        System.out.println(al.getCARRERA_ALUMNO());
        String mensaje = "<!Doctype html>\n"
                + "<html lang='es'>\n"
                + "  <head>\n"
                + "    <meta name=\"viewport\" content=\"width=device-width\" />\n"
                + "    <meta concent-type='UTF-8' />\n"
                + "    <title>Simple Transactional Email</title>\n"
                + "    <style>\n"
                + "      /* -------------------------------------\n"
                + "          GLOBAL RESETS\n"
                + "      ------------------------------------- */\n"
                + "      \n"
                + "      /*All the styling goes here*/\n"
                + "      \n"
                + "      img {\n"
                + "        border: none;\n"
                + "        -ms-interpolation-mode: bicubic;\n"
                + "        max-width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      body {\n"
                + "        background-color: #f6f6f6;\n"
                + "        font-family: sans-serif;\n"
                + "        -webkit-font-smoothing: antialiased;\n"
                + "        font-size: 14px;\n"
                + "        line-height: 1.4;\n"
                + "        margin: 0;\n"
                + "        padding: 0;\n"
                + "        -ms-text-size-adjust: 100%;\n"
                + "        -webkit-text-size-adjust: 100%; \n"
                + "      }\n"
                + "\n"
                + "      table {\n"
                + "      font-family: arial, sans-serif;\n"
                + "      border-collapse: collapse;\n"
                + "      width: 100%;\n"
                + "      }\n"
                + "\n"
                + "      td, th {\n"
                + "      border: 1px solid #dddddd;\n"
                + "      text-align: left;\n"
                + "      padding: 8px;\n"
                + "      } \n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          BODY & CONTAINER\n"
                + "      ------------------------------------- */\n"
                + "\n"
                + "      .body {\n"
                + "        background-color: #f6f6f6;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */\n"
                + "      .container {\n"
                + "        display: block;\n"
                + "        margin: 0 auto !important;\n"
                + "        /* makes it centered */\n"
                + "        max-width: 580px;\n"
                + "        padding: 10px;\n"
                + "        width: 600px; \n"
                + "      }\n"
                + "\n"
                + "      /* This should also be a block element, so that it will fill 100% of the .container */\n"
                + "      .content {\n"
                + "        box-sizing: border-box;\n"
                + "        display: block;\n"
                + "        margin: 0 auto;\n"
                + "        max-width: 580px;\n"
                + "        padding: 10px; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          HEADER, FOOTER, MAIN\n"
                + "      ------------------------------------- */\n"
                + "      .main {\n"
                + "        background: #ffffff;\n"
                + "        border-radius: 3px;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "\n"
                + "      .wrapper {\n"
                + "        box-sizing: border-box;\n"
                + "        padding: 20px; \n"
                + "      }\n"
                + "\n"
                + "      .content-block {\n"
                + "        padding-bottom: 10px;\n"
                + "        padding-top: 10px;\n"
                + "      }\n"
                + "\n"
                + "      .footer {\n"
                + "        clear: both;\n"
                + "        margin-top: 10px;\n"
                + "        text-align: center;\n"
                + "        width: 100%; \n"
                + "      }\n"
                + "        .footer td,\n"
                + "        .footer p,\n"
                + "        .footer span,\n"
                + "        .footer a {\n"
                + "          color: #999999;\n"
                + "          font-size: 12px;\n"
                + "          text-align: center; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          TYPOGRAPHY\n"
                + "      ------------------------------------- */\n"
                + "      h1,\n"
                + "      h2,\n"
                + "      h3,\n"
                + "      h4 {\n"
                + "        color: #000000;\n"
                + "        font-family: sans-serif;\n"
                + "        font-weight: 400;\n"
                + "        line-height: 1.4;\n"
                + "        margin: 0;\n"
                + "        margin-bottom: 30px; \n"
                + "      }\n"
                + "\n"
                + "      h1 {\n"
                + "        font-size: 35px;\n"
                + "        font-weight: 300;\n"
                + "        text-align: center;\n"
                + "        text-transform: capitalize; \n"
                + "      }\n"
                + "\n"
                + "      p,\n"
                + "      ul,\n"
                + "      ol {\n"
                + "        font-family: sans-serif;\n"
                + "        font-size: 14px;\n"
                + "        font-weight: normal;\n"
                + "        margin: 0;\n"
                + "        margin-bottom: 15px; \n"
                + "      }\n"
                + "        p li,\n"
                + "        ul li,\n"
                + "        ol li {\n"
                + "          list-style-position: inside;\n"
                + "          margin-left: 5px; \n"
                + "      }\n"
                + "\n"
                + "      a {\n"
                + "        color: #3498db;\n"
                + "        text-decoration: underline; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          BUTTONS\n"
                + "      ------------------------------------- */\n"
                + "      .btn {\n"
                + "        box-sizing: border-box;\n"
                + "        width: 100%; }\n"
                + "        .btn > tbody > tr > td {\n"
                + "          padding-bottom: 15px; }\n"
                + "        .btn table {\n"
                + "          width: auto; \n"
                + "      }\n"
                + "        .btn table td {\n"
                + "          background-color: #ffffff;\n"
                + "          border-radius: 5px;\n"
                + "          text-align: center; \n"
                + "      }\n"
                + "        .btn a {\n"
                + "          background-color: #ffffff;\n"
                + "          border: solid 1px #3498db;\n"
                + "          border-radius: 5px;\n"
                + "          box-sizing: border-box;\n"
                + "          color: #3498db;\n"
                + "          cursor: pointer;\n"
                + "          display: inline-block;\n"
                + "          font-size: 14px;\n"
                + "          font-weight: bold;\n"
                + "          margin: 0;\n"
                + "          padding: 12px 25px;\n"
                + "          text-decoration: none;\n"
                + "          text-transform: capitalize; \n"
                + "      }\n"
                + "\n"
                + "      .btn-primary table td {\n"
                + "        background-color: #3498db; \n"
                + "      }\n"
                + "\n"
                + "      .btn-primary a {\n"
                + "        background-color: #3498db;\n"
                + "        border-color: #3498db;\n"
                + "        color: #ffffff; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          OTHER STYLES THAT MIGHT BE USEFUL\n"
                + "      ------------------------------------- */\n"
                + "      .last {\n"
                + "        margin-bottom: 0; \n"
                + "      }\n"
                + "\n"
                + "      .first {\n"
                + "        margin-top: 0; \n"
                + "      }\n"
                + "\n"
                + "      .align-center {\n"
                + "        text-align: center; \n"
                + "      }\n"
                + "\n"
                + "      .align-right {\n"
                + "        text-align: right; \n"
                + "      }\n"
                + "\n"
                + "      .align-left {\n"
                + "        text-align: left; \n"
                + "      }\n"
                + "\n"
                + "      .clear {\n"
                + "        clear: both; \n"
                + "      }\n"
                + "\n"
                + "      .mt0 {\n"
                + "        margin-top: 0; \n"
                + "      }\n"
                + "\n"
                + "      .mb0 {\n"
                + "        margin-bottom: 0; \n"
                + "      }\n"
                + "\n"
                + "      .preheader {\n"
                + "        color: transparent;\n"
                + "        display: none;\n"
                + "        height: 0;\n"
                + "        max-height: 0;\n"
                + "        max-width: 0;\n"
                + "        opacity: 0;\n"
                + "        overflow: hidden;\n"
                + "        mso-hide: all;\n"
                + "        visibility: hidden;\n"
                + "        width: 0; \n"
                + "      }\n"
                + "\n"
                + "      .powered-by a {\n"
                + "        text-decoration: none; \n"
                + "      }\n"
                + "\n"
                + "      hr {\n"
                + "        border: 0;\n"
                + "        border-bottom: 1px solid #f6f6f6;\n"
                + "        margin: 20px 0; \n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          RESPONSIVE AND MOBILE FRIENDLY STYLES\n"
                + "      ------------------------------------- */\n"
                + "      @media only screen and (max-width: 620px) {\n"
                + "        table[class=body] h1 {\n"
                + "          font-size: 28px !important;\n"
                + "          margin-bottom: 10px !important; \n"
                + "        }\n"
                + "        table[class=body] p,\n"
                + "        table[class=body] ul,\n"
                + "        table[class=body] ol,\n"
                + "        table[class=body] td,\n"
                + "        table[class=body] span,\n"
                + "        table[class=body] a {\n"
                + "          font-size: 16px !important; \n"
                + "        }\n"
                + "        table[class=body] .wrapper,\n"
                + "        table[class=body] .article {\n"
                + "          padding: 10px !important; \n"
                + "        }\n"
                + "        table[class=body] .content {\n"
                + "          padding: 0 !important; \n"
                + "        }\n"
                + "        table[class=body] .container {\n"
                + "          padding: 0 !important;\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .main {\n"
                + "          border-left-width: 0 !important;\n"
                + "          border-radius: 0 !important;\n"
                + "          border-right-width: 0 !important; \n"
                + "        }\n"
                + "        table[class=body] .btn table {\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .btn a {\n"
                + "          width: 100% !important; \n"
                + "        }\n"
                + "        table[class=body] .img-responsive {\n"
                + "          height: auto !important;\n"
                + "          max-width: 100% !important;\n"
                + "          width: auto !important; \n"
                + "        }\n"
                + "      }\n"
                + "\n"
                + "      /* -------------------------------------\n"
                + "          PRESERVE THESE STYLES IN THE HEAD\n"
                + "      ------------------------------------- */\n"
                + "      @media all {\n"
                + "        .ExternalClass {\n"
                + "          width: 100%; \n"
                + "        }\n"
                + "        .ExternalClass,\n"
                + "        .ExternalClass p,\n"
                + "        .ExternalClass span,\n"
                + "        .ExternalClass font,\n"
                + "        .ExternalClass td,\n"
                + "        .ExternalClass div {\n"
                + "          line-height: 100%; \n"
                + "        }\n"
                + "        .apple-link a {\n"
                + "          color: inherit !important;\n"
                + "          font-family: inherit !important;\n"
                + "          font-size: inherit !important;\n"
                + "          font-weight: inherit !important;\n"
                + "          line-height: inherit !important;\n"
                + "          text-decoration: none !important; \n"
                + "        }\n"
                + "        #MessageViewBody a {\n"
                + "          color: inherit;\n"
                + "          text-decoration: none;\n"
                + "          font-size: inherit;\n"
                + "          font-family: inherit;\n"
                + "          font-weight: inherit;\n"
                + "          line-height: inherit;\n"
                + "        }\n"
                + "        .btn-primary table td:hover {\n"
                + "          background-color: #34495e !important; \n"
                + "        }\n"
                + "        .btn-primary a:hover {\n"
                + "          background-color: #34495e !important;\n"
                + "          border-color: #34495e !important; \n"
                + "        } \n"
                + "      }\n"
                + "\n"
                + "    </style>\n"
                + "  </head>\n"
                + "  <body class=\"\">\n"
                + "    <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\">\n"
                + "      <tr>\n"
                + "        <td>&nbsp;</td>\n"
                + "        <td class=\"container\">\n"
                + "          <div class=\"content\">\n"
                + "\n"
                + "            <!-- START CENTERED WHITE CONTAINER -->\n"
                + "            <table role=\"presentation\" class=\"main\">\n"
                + "\n"
                + "              <!-- START MAIN CONTENT AREA -->\n"
                + "              <tr>\n"
                + "                <td class=\"wrapper\">\n"
                + "                    <h2>Tipo Solicitud: \n" + joinNombreSoli(soli.getIdflujo())
                + "                      </h2>\n"
                + "                      <h2>\n"
                + "                          COMPROBANTE DE SOLICITUD \n"
                + "                          FOLIO DE TRANSACCIÓN N°" + soli.getIdSolicitud()+ "\n" + "" + dia + " del " + mes + " de " + annio + "\n"
                + "                          RESOLUCION DE SOLICITUD : APROBADA"
                + "                      </h2>\n"
                + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                    \n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Alumno:\n"
                + "                      </th>\n"
                + "                      <td>\n" + al.getNOMBRE_ALUMNO()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Rut:\n"
                + "                      </th>\n"
                + "                      <td>\n" + al.getRUT_ALUMNO().replaceAll("[.-]", "")
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Establecimiento:\n"
                + "                      </th>\n"
                + "                      <td>\n"
                + "                        DuocUC: Antonio Varas\n"
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Jornada:\n"
                + "                      </th>\n"
                + "                      <td>\n" + joinJornada(al.getID_JORNADA())
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Carrera:\n"
                + "                      </th>\n"
                + "                      <td>\n" + al.getCARRERA_ALUMNO()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Telefono:\n"
                + "                      </th>\n"
                + "                      <td>\n +56 " + al.getTELEFONO()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Creador de la solicitud:\n"
                + "                      </th>\n"
                + "                      <td>\n" + dusu.traerUsuario(soli.getIdUsuarioCreador()).getNombre()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Responsable actual:\n"
                + "                      </th>\n"
                + "                      <td>\n" + dusu.traerUsuario(soli.getIdUsuarioResponsable()).getNombre()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Estado actual:\n"
                + "                      </th>\n"
                + "                      <td>\n" + daosoli.consultarNombreEstado(soli.getCodEstado())
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Próximo estado:\n"
                + "                      </th>\n"
                + "                      <td>\n" + daosoli.consultarNombreEstado(proxEstado)
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "                        Fecha:\n"
                + "                      </th>\n"
                + "                      <td> \n" + dia + " del " + mes + " de " + annio
                + "                      </td>\n"
                + "                    </tr>\n"
                + "\n"
                + "                    <tr>\n"
                + "                      <th>\n"
                + "Descripción:"
                + "                      </th>\n"
                + "                      <td>\n" + soli.getDescripcion()
                + "                      </td>\n"
                + "                    </tr>\n"
                + "                  </table>\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "              <tr>\n"
                + "                <th>\n"
                + "                    <span>\n"
                + "                        Se le informará oportunamente a su teléfono o correo \n"
                + "                        electrónico, la fecha que debe retirar lo solicitado \n"
                + "                        o el estado de su solicitud.\n"
                + "                    </span>\n"
                + "                    <span>\n"
                + "                        Por favor no responder este correo, si tiene \n"
                + "                        dudas o necesita consultar por su estado,  enviar \n"
                + "                        mail a <a href=\"mailto: csa_avaras@duoc.cl\">csa_avaras@duoc.cl</a> \n"
                + "                    </span>\n"
                + "                </th>\n"
                + "              </tr>\n"
                + "            <!-- END MAIN CONTENT AREA -->\n"
                + "            </table>\n"
                + "            <!-- END CENTERED WHITE CONTAINER -->\n"
                + "            <!-- START FOOTER -->\n"
                + "            <div class=\"footer\">\n"
                + "                \n"
                + "              <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                <tr>\n"
                + "                  <td class=\"content-block\">\n"
                + "                    <span class=\"apple-link\">DuocUC: Sede Antonio Varas, Antonio Varas 666 Providencia, Región Metropolitana</span>\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "                <tr>\n"
                + "                  <td class=\"content-block powered-by\">\n"
                + "                    Powered by <a href=\"http://htmlemail.io\">HTMLemail</a>.\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "              </table>\n"
                + "            </div>\n"
                + "            <!-- END FOOTER -->\n"
                + "\n"
                + "          </div>\n"
                + "        </td>\n"
                + "        <td>&nbsp;</td>\n"
                + "      </tr>\n"
                + "    </table>\n"
                + "  </body>\n"
                + "</html>";

        final String username = "webdocspruebas@gmail.com";
        final String password = "123duoc456";

        Properties prop = new Properties();
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "587");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.starttls.enable", "true"); //TLS
        prop.put("mail.smtp.ssl.trust", "*");

        Session session = Session.getInstance(prop,
                new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {

            Message message = new MimeMessage(session);
            message.setSubject("Notificacion solicitud");
            message.setContent(mensaje, "text/html; charset=UTF-8");
            message.setFrom(new InternetAddress(username,"Solicitud Duoc UC"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(al.getCORREO_ALUMNO()));

            Transport.send(message);

            System.out.println("Done");

        } catch (MessagingException e) {
            e.printStackTrace();
        }

    }
    
    
    Calendar c = Calendar.getInstance();

    String dia = Integer.toString(c.get(Calendar.DATE));
    String mess = Integer.toString(c.get(Calendar.MONTH));
    String annio = Integer.toString(c.get(Calendar.YEAR));
    int mes = Integer.parseInt(mess) + 1;
    //String hora = Integer.toString(c.get(Calendar.HOUR));
    //String min = Integer.toString(c.get(Calendar.MINUTE));

    public String joinJornada(int idJornada) {
        String nombre = null;
        try {
            PreparedStatement ps = conn.prepareStatement("Select nom_jornada from jornada where id_jornada = ?;");
            ps.setInt(1, idJornada);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                nombre = rs.getString("nom_jornada");
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return nombre;
    }

    public String joinNombreSoli(int idFlujo) {
        String nombre = null;
        try {
            PreparedStatement ps = conn.prepareStatement("Select nombre from flujo where id_flujo = ?;");
            ps.setInt(1, idFlujo);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                nombre = rs.getString("nombre");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        return nombre;
    }
    
    public String joinMotivo(int idMotivo) {
        String motivo = null;
        try {
            PreparedStatement ps = conn.prepareStatement("Select motivo from motivos where IdMotivo = ?;");
            ps.setInt(1, idMotivo);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                motivo = rs.getString("motivo");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        return motivo;
    }
}
